### ISSUE TITLE
Add full example call

### ISSUE THREAD

**Issue by koppor** [koppor/github-contributors-list#22]
As of today, there is a NPE:

```
C:\git-repositories\jabref-all\jabref (main) >  jbang gcl@koppor/github-contributors-list --startrevision=v5.13 --endrevision=v5.15 --repos
itory=jabref/jabref/ .
INFO: Opening local git repository .... (call)
INFO: Connecting to jabref/jabref/... (call)
INFO: Analyzing 100 days: From 2024-04-01 to 2024-07-10 (getCommitRangeInformation)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.jna" is null
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:443)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:362)
        at me.tongfei.progressbar.TerminalUtils.getTerminal(TerminalUtils.java:83)
        at me.tongfei.progressbar.TerminalUtils.hasCursorMovementSupport(TerminalUtils.java:37)
        at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:30)
        at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:26)
        at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:80)
        at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:38)
        at gcl.call(gcl.java:220)
        at gcl.call(gcl.java:69)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at gcl.main(gcl.java:167)
```

The user should be informed what is wrong. (Also happens at minimal command line: ` jbang gcl@koppor/github-contributors-list`.

**Comment by Siedlerchr** [comment]
Refs https://github.com/jline/jline3/issues/930
