### ISSUE TITLE
have better defaults?

### ISSUE THREAD

**Issue by maxandersen** [koppor/github-contributors-list#3]
if you run without startRevision set you get:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.lib.AnyObjectId.hashCode()" because "id" is null
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:115)
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:76)
	at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:31)
	at org.eclipse.jgit.internal.storage.file.LooseObjects.hasCached(LooseObjects.java:99)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:359)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1144)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:1055)
	at gcl.call(gcl.java:166)
	at gcl.call(gcl.java:64)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at gcl.main(gcl.java:138)
```

cause is that the defaults are hardwired to jabref owner, org and start/end revision.

**Comment by koppor** [comment]
Fixed by https://github.com/koppor/github-contributors-list/pull/5

- Can now run without any parameters: The current directory is used as the repository path.
- The defaults for `--startrevision` and `--endrevision` are now the complete branch history (starting from `HEAD`).
